.common_setup: &common_setup
  before_script:
    - apt-get update -y && apt-get install -y python3 python3-pip
    - pip3 install polars
    - pip3 install yaml

stages:
  - preparation
  - test
  - deploy

preparation:
  image: ruby:3.1
  stage: preparation
  <<: *common_setup
  script:
    - echo "INICIO ETAPA PROCESAMIENTO DE DATOS..."
    - python3 __main__.py preparation
    - echo "FIN ETAPA PROCESAMIENTO DE DATOS!"
