stages:
  - preparation

preparation:
  stage: preparation
  script:
    - echo "INICIO ETAPA PROCESAMIENTO DE DATOS..."
    - python __main__.py preparation
    - echo "FIN ETAPA PROCESAMIENTO DE DATOS!"
