stages:
  - preparation
  - feature_engineering
  - model_input
  - training
  - model_selection

# Configuración común para todos los stages
.common_setup: &common_setup
  - apt-get update -y && apt-get install -y python3 python3-pip python3-venv
  - python3 -m venv proyecto_tc
  - source proyecto_tc/bin/activate
  - pip3 install --upgrade pip
  - pip3 install PyYAML
  - pip3 install pyarrow
  - pip3 install pandas

# Instalación específica para el stage de preparation
.preparation_setup: &preparation_setup
  - *common_setup
  - pip3 install xlsx2csv
  - pip3 install openpyxl

# Instalación específica para el stage de feature_engineering
.feature_engineering_setup: &feature_engineering_setup
  - *common_setup
  - pip3 install numpy
  - pip3 install scikit-learn

# Instalación específica para el stage de model_input
.model_input_setup: &model_input_setup
  - *common_setup
  - pip3 install scikit-learn
  - pip3 install imbalanced-learn

# Instalación específica para el stage de models
.models_setup: &models_setup
  - *common_setup
  - pip3 install numpy
  - pip3 install scikit-learn
  - pip3 install xgboost
  - pip3 install scipy
  - pip3 install scikit-posthocs

# Instalación específica para el stage de model_selection
.model_selection_setup: &model_selection_setup
  - *common_setup
  - pip3 install numpy
  - pip3 install scikit-learn
  - pip3 install bayesian-optimization


## Ejecución de los stages

preparation_pipeline:
  image: ruby:3.1
  stage: preparation
  before_script:
    *preparation_setup
  script:
    - echo "INICIO ETAPA PROCESAMIENTO DE DATOS..."
    - proyecto_tc/bin/python3 __main__.py 'preparation_pipeline'
    - echo "FIN ETAPA PROCESAMIENTO DE DATOS!"

feature_engineering_pipeline:
  image: ruby:3.1
  stage: feature_engineering
  before_script:
    *feature_engineering_setup
  script:
    - echo "INICIO ETAPA INGENIERÍA DE CARACTERÍSTICAS..."
    - proyecto_tc/bin/python3 __main__.py 'feature_engineering_pipeline'
    - echo "FIN ETAPA INGENIERÍA DE CARACTERÍSTICAS!"

model_input_pipeline:
  image: ruby:3.1
  stage: model_input
  before_script:
    *model_input_setup
  script:
    - echo "INICIO ETAPA MODEL INPUT..."
    - proyecto_tc/bin/python3 __main__.py 'model_input_pipeline'
    - echo "FIN ETAPA MODEL INPUT!"

training:
  image: ruby:3.1
  stage: training
  before_script:
    *models_setup
  script:
    - echo "INICIO ETAPA EXPERIMENTACIÓN MODELOS..."
    - proyecto_tc/bin/python3 __main__.py 'models_pipeline'
    - echo "FIN ETAPA EXPERIMENTACIÓN MODELOS!"

model_selection_pipeline:
    image: ruby:3.1
    stage: model_selection
    before_script:
        *model_selection_setup
    script:
        - echo "INICIO ETAPA SELECCIÓN DE MODELOS..."
        - proyecto_tc/bin/python3 __main__.py 'model_selection_pipeline'
        - echo "FIN ETAPA SELECCIÓN DE MODELOS!"
